config/routes.rb
Rails.application.routes.draw do
  resources :servers do
    member do 
      patch :activate
      resources :snapshots, only: :index do
        collection do
          get :cpu
          get :memory
          get :disks
        end
      end
    end
  end


  devise_for :users
  mount Monitoring::API => '/'
end

app/models/server.rb
# == Schema Information
#
# Table name: servers
#
#  id                   :integer          not null, primary key
#  distro_name          :string(255)
#  kernel_release       :string(255)
#  uptime               :integer
#  ip                   :string(255)
#  authentication_token :string(255)
#  user_id              :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  state                :string(255)
#

class Server < ActiveRecord::Base
  acts_as_token_authenticatable

  belongs_to :user
  validates :user, presence: true
  validates :ip, presence: true
  validates :ip, uniqueness: true

  scope :active, -> { where(state: :active) }
  scope :inactive, -> { where(state: :inactive) }

  before_create do
    self.state = 'inactive'
  end

  def self.authenticate(token)
    Server.find_by_authentication_token(token)
  end

  def activate!
    update_attributes state: :active
  end
end

app/models/snapshot.rb
class Snapshot
  include Mongoid::Document
  # include Mongoid::Attributes::Dynamic
  field :server_id, type: Integer
  field :memory, type: Hash
  field :cpu, type: Hash
  field :disks, type: Array
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :servers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    servers_path
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy, :activate]
  before_action :authenticate_user!

  def index
    @servers = current_user.servers
  end

  def show
    redirect_to servers_path, alert: "Please activate #{@server.ip} server." unless @server.state == 'active'
    # HACK
    @snapshot = Snapshot.where(server_id: @server.id).desc(:id).limit(1).first
  end

  def new
    @server = Server.new
  end

  def edit
  end

  def create
    @server = Server.new(server_params.merge user: current_user)

    respond_to do |format|
      if @server.save
        format.html { redirect_to servers_path, notice: 'Server was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to servers_path, notice: 'Server was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_path, notice: 'Server was successfully destroyed.' }
    end
  end

  def activate
    client = XMLRPC::Client.new @server.ip, '/', 8080
    client.call 'system.activate', @server.authentication_token
    @server.activate!
    redirect_to @server, notice: 'Please restart your Monitoring Client'
  end

  private
    def set_server
      @server = Server.find(params[:id])
    end

    def server_params
      params.require(:server).permit(:ip)
    end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :set_snapshots
  before_action :authenticate_user!
  before_action :respond_with_json, except: :index

  respond_to :json
  
  def index
    respond_with @snapshots
  end

  def cpu
  end

  def memory
  end

  def disks
  end

  private

  def respond_with_json
    respond_with @snapshots.to_json(only: action_name)
  end

  def set_snapshots
    @server = Server.find(params[:id])
    @snapshots = Snapshot.where(server_id: @server.id).desc(:id).limit(params[:limit])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
  def disk_stats(disk)
    "#{number_to_human_size disk['used'] * 1024 }/#{ number_to_human_size disk['total'] * 1024 }"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Monitoring
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/header'
    .container-fluid
      - if notice
        .alert.alert-dismissable.alert-success
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          %strong= notice
      - if alert
        .alert.alert-dismissable.alert-danger
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          %strong= alert
      = yield

app/views/layouts/pages.html.haml
!!!
%html
  %head
    %title Cloud Monitoring
    %meta{content: 'user-scalable=no', name: 'viewport'}
    = stylesheet_link_tag    'pages'
    = javascript_include_tag 'pages'
    = csrf_meta_tags
  %body
    = render 'shared/pages/navbar'
    = yield
    = render 'shared/pages/footer'

app/views/pages/index.html.haml
= render 'shared/pages/header'
.content
  .container
    .row
      .col-md-6.col-xs-12
        %h3.night-blue We use 100% real clouds
        %p.orange
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        %p.p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      .col-md-6.col-xs-12
        %h3.night-blue We don't hurt kittens
        %p.orange
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        %p.p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    .row
      .col-md-6.col-xs-12
        %h3.night-blue Real time monitoring
        %p.orange
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        %p.p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      .col-md-6.col-xs-12
        %h3.night-blue Free demo
        %p.orange
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        %p.p
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/servers/_form.html.haml
= form_for @server do |f|
  - if @server.errors.any?
    #error_explanation
      %h2= "#{pluralize(@server.errors.count, "error")} prohibited this server from being saved:"
      %ul
        - @server.errors.full_messages.each do |msg|
          %li= msg
  = f.label :ip
  = f.text_field :ip
  .actions
    = f.submit 'Save', class: 'btn'

app/views/servers/boards/_cpu.html.haml
.well
  %h3 CPU Load
  #cpu_chart{style: "height: 300px;", data: { update_url: cpu_snapshots_path(@server, format: :json) } }

app/views/servers/boards/_disks.html.haml
.well
  %h3 Disk Partitions
  %table.table
    %thead
      %tr
        %th Name
        %th
        %th Stats
        %th Usage
        %th Mount Path
    %tbody
      - if @snapshot
        - @snapshot.disks.each do |disk|
          %tr
            %td= disk['name']
            %td
              .progress{ style: "width: 70px" }
                .progress-bar.progress-bar-info{ data: { use: disk['use'] } }
            %td #{ disk_stats disk }
            %td= disk['use']
            %td= disk['mount_path']

app/views/servers/boards/_general.html.haml
.well
  %h3 General Info
  %table.table
    %thead
    %tbody  
      %tr
        %td
          %strong Distributive
        %td= @server.distro_name 
      %tr
        %td
          %strong Kernel
        %td= @server.kernel_release
      %tr
        %td
          %strong Authentication Token
        %td= @server.authentication_token 
      %tr
        %td
          %strong IP
        %td= @server.ip 
      %tr
        %td
          %strong State
        %td= @server.state

app/views/servers/boards/_memory.html.haml
.well
  %h3 RAM Usage
  #memory_chart{style: "height: 300px;", data: { update_url: memory_snapshots_path(@server, format: :json) } }

app/views/servers/edit.html.haml
%h1 Editing server

= render 'form'

= link_to 'Show', @server
\|
= link_to 'Back', servers_path

app/views/servers/index.html.haml
%h1 Listing servers

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Distributive
      %th Kernel Version
      %th Ip
      %th Status
      %th
      %th
      
  %tbody
    - @servers.each do |server|
      %tr
        %td= server.distro_name
        %td= server.kernel_release
        %td= server.ip
        %td= server.state
        - if server.state == 'active'
          %td
        - else
          %td= link_to 'Activate', activate_server_path(server), method: :patch 
        %td= link_to 'Show', server
        %td= link_to 'Edit', edit_server_path(server)
        %td= link_to 'Destroy', server, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to 'New Server', new_server_path

app/views/servers/new.html.haml
%h1 New server

= render 'form'

= link_to 'Back', servers_path

app/views/servers/show.html.haml
.row
  .col-md-6
    = render 'servers/boards/general'
  .col-md-6
    = render 'servers/boards/disks'
.row
  .col-md-6
    = render 'servers/boards/memory'
  .col-md-6
    = render 'servers/boards/cpu'

app/views/shared/_header.html.haml
.navbar.navbar-default
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "javascript:void(0)"} Monitoring
  - if user_signed_in?
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li.active
          = link_to 'Servers', servers_path
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
            = current_user.email
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to 'Sing Out', destroy_user_session_path, method: :delete

app/views/shared/pages/_carousel.html.haml
#clouds-carousel.carousel.slide{ data: { ride: :carousel, interval: 2000 } }
  %ol.carousel-indicators
    %li.active{ data: { target: '#clouds-carousel', :'slide-to' => 0 } }
    %li{ data: { target: '#clouds-carousel', :'slide-to' => 1 } }
    %li{ data: { target: '#clouds-carousel', :'slide-to' => 2 } }
  .carousel-inner{role: 'listbox'}
    .item.active
      .carousel-image
        = image_tag 'cloud.png'
    .item
      .carousel-image
        = image_tag 'cloud.png'
    .item
      .carousel-image
        = image_tag 'cloud.png'
  %a.left.carousel-control{ href: '#clouds-carousel', role: 'button', data: { slide: 'prev' } }
    %span.glyphicon.glyphicon-chevron-left{ :'aria-hidden' => 'true' }
    %span.sr-only Previous
  %a.right.carousel-control{ href: '#clouds-carousel', role: 'button', data: { slide: 'next' } }
    %span.glyphicon.glyphicon-chevron-right{ :'aria-hidden' => 'true' }
    %span.sr-only Next

app/views/shared/pages/_footer.html.haml
%footer
  .container
    .row
      .footer-brand
        = image_tag 'logo.png'
      .col-md-7
        = form_tag '#', class: 'form-horizontal' do
          .form-group.white Ask as your questions
          .form-group
            = email_field_tag 'feedback[email]', nil, class: 'form-control form-inverse tiny-rounded', placeholder: 'Leave your email cobber'
          .form-group
            = text_area_tag 'feedback[message]', nil, class: 'form-control form-inverse tiny-rounded', placeholder: 'Leave your message', rows: 11
          .form-group
            = submit_tag 'Send', class: 'btn btn-lg btn-black tiny-rounded pull-right'

app/views/shared/pages/_header.html.haml
%header
  .container
    .row
      .col-md-offset-2.col-md-8
        %h1.white.text-center Cloud linux servers monitoring
    .row
      .col-md-12
        = render 'shared/pages/carousel'
    .row
      = form_tag '#', class: 'form-inline' do
        .form-group.col-md-4.col-md-offset-1.col-xs-12.remove-padding
          = email_field_tag 'username', nil, placeholder: 'Email', class: 'form-control sign-up-input tiny-rounded'
        .form-group.col-md-4.col-xs-12.remove-padding
          = password_field_tag 'password', nil, placeholder: 'Password', class: 'form-control sign-up-input tiny-rounded'
        = submit_tag 'Create Account', class: 'col-md-3 col-xs-12 remove-padding btn btn-lg btn-deep-blue input-lg tiny-rounded sign-up-submit'

app/views/shared/pages/_navbar.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      = link_to root_path, class: 'havbar-brand' do
        = image_tag 'logo.png'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'About', '#'
        %li
          = link_to 'How it Works', '#'
        %li
          = link_to 'Sign In', new_user_session_path
        %li
          %p.navbar-btn
            = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg tiny-rounded btn-success-flat'